"""The desktop tool page is generated by reflecting over argparse.

argparse help strings are written for `--help` and are English, so without the
translation tables the Chinese window shows things like
"Run OpenAI-compatible web search." These tests keep that from coming back.
"""

import re

import pytest

from smart_search.i18n import use_language


@pytest.fixture(autouse=True)
def chinese_presentation():
    with use_language("zh"):
        yield

from smart_search import service
from smart_search.desktop_catalog import (
    _DESCRIPTIONS,
    _FIELD_HELP,
    _FIELD_LABELS,
    _LABELS,
    command_catalog,
)
from smart_search.ui_metadata import STATUS_LABELS, status_label

HAN = re.compile(r"[一-鿿]")


def _is_english_prose(text: str) -> bool:
    """A non-empty string carrying no Han characters is untranslated prose."""
    return bool(text) and not HAN.search(text)


def test_every_command_has_a_chinese_description():
    offenders = [
        (entry["id"], entry["description"])
        for entry in command_catalog()
        if _is_english_prose(entry["description"])
    ]
    assert not offenders, (
        f"these commands still show English on the tools page: {offenders}. "
        "Add them to desktop_catalog._DESCRIPTIONS."
    )


def test_every_command_description_is_non_empty():
    missing = [entry["id"] for entry in command_catalog() if not entry["description"].strip()]
    assert not missing, f"no description at all for: {missing}"


def test_every_field_help_is_chinese():
    offenders = {}
    for entry in command_catalog():
        for field in entry["fields"]:
            if _is_english_prose(field["help"]):
                offenders.setdefault(field["name"], field["help"])
    assert not offenders, (
        f"these field descriptions are still English: {sorted(offenders)}. "
        "Add them to desktop_catalog._FIELD_HELP."
    )


def test_labelled_fields_also_have_help():
    # A field worth naming in Chinese is worth explaining in Chinese.
    described = {
        field["name"]
        for entry in command_catalog()
        for field in entry["fields"]
        if field["help"].strip()
    }
    missing = sorted(set(_FIELD_LABELS) - described)
    assert not missing, f"these fields have a Chinese label but no description: {missing}"


def test_translation_tables_have_no_dead_entries():
    catalog_ids = {entry["id"] for entry in command_catalog()}
    stale = sorted(set(_DESCRIPTIONS) - catalog_ids)
    assert not stale, f"_DESCRIPTIONS names commands that no longer exist: {stale}"

    field_names = {field["name"] for entry in command_catalog() for field in entry["fields"]}
    stale_fields = sorted(set(_FIELD_HELP) - field_names)
    assert not stale_fields, f"_FIELD_HELP names fields that no longer exist: {stale_fields}"


def test_label_table_still_matches_the_catalog():
    catalog_ids = {entry["id"] for entry in command_catalog()}
    stale = sorted(set(_LABELS) - catalog_ids)
    assert not stale, f"_LABELS names commands that no longer exist: {stale}"


# ---- status vocabulary --------------------------------------------------
def test_probe_kinds_are_translated():
    kinds = set()
    for kind in service.PROBE_KIND.values():
        kinds.add(kind.split(":", 1)[0] if kind.startswith("shared:") else kind)
    missing = sorted(kinds - set(STATUS_LABELS))
    assert not missing, f"untranslated probe kinds: {missing}"


def test_provider_health_states_are_translated():
    for state in ("closed", "cooldown"):
        assert state in STATUS_LABELS


def test_approved_error_types_are_translated():
    from smart_search.provider_errors import APPROVED_PROVIDER_ERROR_TYPES

    missing = sorted(set(APPROVED_PROVIDER_ERROR_TYPES) - set(STATUS_LABELS))
    assert not missing, f"untranslated error types: {missing}"


def test_config_sources_are_translated():
    for source in ("environment", "config_file", "default"):
        assert source in STATUS_LABELS


def test_every_status_label_has_both_languages():
    for key, entry in STATUS_LABELS.items():
        assert entry.get("zh", "").strip(), f"{key} has no Chinese label"
        assert entry.get("en", "").strip(), f"{key} has no English label"
        assert HAN.search(entry["zh"]) or key in {"ok"}, f"{key} zh label looks untranslated"


@pytest.mark.parametrize("value,expected", [("closed", "未冷却"), ("cooldown", "冷却中"), ("up_to_date", "已是最新")])
def test_status_label_translates(value, expected):
    assert status_label(value) == expected


def test_status_label_falls_back_to_the_raw_value():
    # An unlisted value must degrade to showing itself, never to an empty cell.
    assert status_label("a_brand_new_status") == "a_brand_new_status"
    assert status_label("") == ""
    assert status_label("closed", "en") == "Not cooling down"
